export const BIBLICAL_QUESTIONS = [
  { question: "¿Quién construyó el arca?", answer: "Noé" },
  { question: "¿Quién fue tragado por un gran pez?", answer: "Jonás" },
  { question: "¿En qué ciudad nació Jesús?", answer: "Belén" },
  { question: "¿Quién fue el primer hombre en la Tierra?", answer: "Adán" },
  { question: "¿Quién fue la primera mujer?", answer: "Eva" },
  { question: "¿Cuántos días duró el diluvio?", answer: "40 días y 40 noches" },
  { question: "¿Quién separó el Mar Rojo?", answer: "Moisés" },
  { question: "¿Qué instrumento tocaba David?", answer: "Arpa" },
  { question: "¿Quién fue lanzado al foso de los leones?", answer: "Daniel" },
  { question: "¿Cuántos discípulos tenía Jesús?", answer: "12" },
  { question: "¿Quién negó tres veces a Jesús?", answer: "Pedro" },
  { question: "¿Qué hizo Jesús en las bodas de Caná?", answer: "Convirtió el agua en vino" },
  { question: "¿Quién fue vendido por sus hermanos?", answer: "José" },
  { question: "¿Qué comida llovió del cielo para los israelitas en el desierto?", answer: "Maná" },
  { question: "¿Quién mató a Goliat con una piedra?", answer: "David" },
  { question: "¿Cuántos mandamientos dio Dios a Moisés?", answer: "10" },
  { question: "¿Cuál es el primer libro de la Biblia?", answer: "Génesis" },
  { question: "¿En qué río fue bautizado Jesús?", answer: "Río Jordán" },
  { question: "¿Qué animal usó Jesús para entrar a Jerusalén?", answer: "Un burro" },
  { question: "¿Cuántos días estuvo Jesús en la tumba antes de resucitar?", answer: "3 días" },
  { question: "¿Qué profesión tenía Mateo antes de seguir a Jesús?", answer: "Recolector de impuestos" },
  { question: "¿Cómo se llamaba el hermano de Moisés?", answer: "Aarón" },
  { question: "¿Qué le dio Dios a Noé como señal de promesa?", answer: "El arco iris" },
];